version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: ecommerce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - app-network
  
  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: ecommerce_db
    ports:
      - "8080:8080"
    command: ["./ecommerce_api"]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
